"""v2 reply comment

Revision ID: 1cbb8f4d689f
Revises: df75049e6696
Create Date: 2026-08-14 13:03:09.994673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cbb8f4d689f'
down_revision: Union[str, Sequence[str], None] = 'df75049e6696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_reply_id', sa.UUID(), nullable=False),
    sa.Column('session_key_id', sa.UUID(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', postgresql.BYTEA(), nullable=False),
    sa.ForeignKeyConstraint(['session_key_id'], ['session.key_id'], ),
    sa.ForeignKeyConstraint(['topic_reply_id'], ['topic_reply.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_reply_id')
    )
    op.create_index(op.f('ix_reply_comment_created_ts'), 'reply_comment', ['created_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_comment_created_ts'), table_name='reply_comment')
    op.drop_table('reply_comment')
    # ### end Alembic commands ###
