"""init

Revision ID: df75049e6696
Revises: 
Create Date: 2026-08-07 10:09:20.095196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df75049e6696'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.UUID(), nullable=False),
    sa.Column('session_pub_key', sa.String(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_table('topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('topic_pub_key', sa.String(), nullable=False),
    sa.Column('topic_pub_key_sig', sa.String(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_ts', sa.DateTime(timezone=True), server_default=sa.text("now() + INTERVAL '1 week'"), nullable=False),
    sa.Column('data', postgresql.BYTEA(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_updated_ts'), 'topic', ['updated_ts'], unique=False)
    op.create_table('topic_reply',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('session_key_id', sa.UUID(), nullable=False),
    sa.Column('topic_reply_pub_key', sa.String(), nullable=False),
    sa.Column('topic_reply_pub_key_sig', sa.String(), nullable=False),
    sa.Column('data', postgresql.BYTEA(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_ts', sa.DateTime(timezone=True), server_default=sa.text("now() + INTERVAL '1 week'"), nullable=False),
    sa.ForeignKeyConstraint(['session_key_id'], ['session.key_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_reply_created_ts'), 'topic_reply', ['created_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_reply_created_ts'), table_name='topic_reply')
    op.drop_table('topic_reply')
    op.drop_index(op.f('ix_topic_updated_ts'), table_name='topic')
    op.drop_table('topic')
    op.drop_table('session')
    # ### end Alembic commands ###
